import type * as recordTypes from '../types/recordTypes';
export declare function getLotOccupantTypes(): recordTypes.LotOccupantType[];
export declare function getLotOccupantTypeById(lotOccupantTypeId: number): recordTypes.LotOccupantType | undefined;
export declare function getLotOccupantTypeByLotOccupantType(lotOccupantType: string): recordTypes.LotOccupantType | undefined;
export declare function getLotStatuses(): recordTypes.LotStatus[];
export declare function getLotStatusById(lotStatusId: number): recordTypes.LotStatus | undefined;
export declare function getLotStatusByLotStatus(lotStatus: string): recordTypes.LotStatus | undefined;
export declare function getLotTypes(): recordTypes.LotType[];
export declare function getLotTypeById(lotTypeId: number): recordTypes.LotType | undefined;
export declare function getLotTypesByLotType(lotType: string): recordTypes.LotType | undefined;
export declare function getOccupancyTypes(): recordTypes.OccupancyType[];
export declare function getAllOccupancyTypeFields(): recordTypes.OccupancyTypeField[];
export declare function getOccupancyTypeById(occupancyTypeId: number): recordTypes.OccupancyType | undefined;
export declare function getOccupancyTypeByOccupancyType(occupancyTypeString: string): recordTypes.OccupancyType | undefined;
export declare function getOccupancyTypePrintsById(occupancyTypeId: number): string[];
export declare function getWorkOrderTypes(): recordTypes.WorkOrderType[];
export declare function getWorkOrderTypeById(workOrderTypeId: number): recordTypes.WorkOrderType | undefined;
export declare function getWorkOrderMilestoneTypes(): recordTypes.WorkOrderMilestoneType[];
export declare function getWorkOrderMilestoneTypeByWorkOrderMilestoneTypeId(workOrderMilestoneTypeId: number): recordTypes.WorkOrderMilestoneType | undefined;
export declare function getWorkOrderMilestoneTypeByWorkOrderMilestoneType(workOrderMilestoneTypeString: string): recordTypes.WorkOrderMilestoneType | undefined;
export declare function clearCacheByTableName(tableName: string): void;
